//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagoApp_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBIREntities : DbContext
    {
        public DBIREntities()
            : base("name=DBIREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Cobradores> Cobradores { get; set; }
        public virtual DbSet<DetalleVarios> DetalleVarios { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Pendientes> Pendientes { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
    
        public virtual ObjectResult<COBRO_POR_COBRADOR_Result> COBRO_POR_COBRADOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<COBRO_POR_COBRADOR_Result>("COBRO_POR_COBRADOR");
        }
    
        public virtual int EGRESOS(Nullable<System.DateTime> fECHAINICIO, Nullable<System.DateTime> fECHAFINAL)
        {
            var fECHAINICIOParameter = fECHAINICIO.HasValue ?
                new ObjectParameter("FECHAINICIO", fECHAINICIO) :
                new ObjectParameter("FECHAINICIO", typeof(System.DateTime));
    
            var fECHAFINALParameter = fECHAFINAL.HasValue ?
                new ObjectParameter("FECHAFINAL", fECHAFINAL) :
                new ObjectParameter("FECHAFINAL", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EGRESOS", fECHAINICIOParameter, fECHAFINALParameter);
        }
    
        public virtual ObjectResult<HISTORIAL_CLIENTES_Result> HISTORIAL_CLIENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HISTORIAL_CLIENTES_Result>("HISTORIAL_CLIENTES");
        }
    
        public virtual ObjectResult<INGRESOS_Result> INGRESOS(Nullable<System.DateTime> fECHAINICIO, Nullable<System.DateTime> fECHAFINAL)
        {
            var fECHAINICIOParameter = fECHAINICIO.HasValue ?
                new ObjectParameter("FECHAINICIO", fECHAINICIO) :
                new ObjectParameter("FECHAINICIO", typeof(System.DateTime));
    
            var fECHAFINALParameter = fECHAFINAL.HasValue ?
                new ObjectParameter("FECHAFINAL", fECHAFINAL) :
                new ObjectParameter("FECHAFINAL", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INGRESOS_Result>("INGRESOS", fECHAINICIOParameter, fECHAFINALParameter);
        }
    
        public virtual ObjectResult<SP_Cobradores_Result> SP_Cobradores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Cobradores_Result>("SP_Cobradores");
        }
    }
}
